source :rubygems

gem 'omniauth', '>= 1.1.1'
gem 'google-api-client', '>= 0.4.6'
gem 'google-api-omniauth', '>= 0.1.0'
gem 'sinatra', '>= 1.3.0'
gem 'extlib', '>= 0.9.15'
gem 'jruby-openssl', :platforms => :jruby
gem 'idn', :platform => :mri_18
